spring.jpa.hibernate.ddl-auto: update
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/Persoonsadministratie
    username: Ester
    password: E$ter
    driver-class-name: com.mysql.jdbc.Driver
#spring.jpa.show-sql: true
  mvc:
    format.date: yyyy-MM-dd

camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks